/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InputFeeHistory
 */
public class InputFeeHistoryTest {
    private final InputFeeHistory model = new InputFeeHistory();

    /**
     * Model tests for InputFeeHistory
     */
    @Test
    public void testInputFeeHistory() {
        // TODO: test InputFeeHistory
    }

    /**
     * Test the property '$schema'
     */
    @Test
    public void $schemaTest() {
        // TODO: test $schema
    }

    /**
     * Test the property 'blockCount'
     */
    @Test
    public void blockCountTest() {
        // TODO: test blockCount
    }

    /**
     * Test the property 'newestBlock'
     */
    @Test
    public void newestBlockTest() {
        // TODO: test newestBlock
    }

    /**
     * Test the property 'rewardPercentiles'
     */
    @Test
    public void rewardPercentilesTest() {
        // TODO: test rewardPercentiles
    }

}
