/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.qanplatform.model.ResponseBlock;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OutputGetBlockByNumber
 */
public class OutputGetBlockByNumberTest {
    private final OutputGetBlockByNumber model = new OutputGetBlockByNumber();

    /**
     * Model tests for OutputGetBlockByNumber
     */
    @Test
    public void testOutputGetBlockByNumber() {
        // TODO: test OutputGetBlockByNumber
    }

    /**
     * Test the property '$schema'
     */
    @Test
    public void $schemaTest() {
        // TODO: test $schema
    }

    /**
     * Test the property 'block'
     */
    @Test
    public void blockTest() {
        // TODO: test block
    }

}
