/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseTransaction
 */
public class ResponseTransactionTest {
    private final ResponseTransaction model = new ResponseTransaction();

    /**
     * Model tests for ResponseTransaction
     */
    @Test
    public void testResponseTransaction() {
        // TODO: test ResponseTransaction
    }

    /**
     * Test the property 'accessList'
     */
    @Test
    public void accessListTest() {
        // TODO: test accessList
    }

    /**
     * Test the property 'blockHash'
     */
    @Test
    public void blockHashTest() {
        // TODO: test blockHash
    }

    /**
     * Test the property 'blockNumber'
     */
    @Test
    public void blockNumberTest() {
        // TODO: test blockNumber
    }

    /**
     * Test the property 'chainId'
     */
    @Test
    public void chainIdTest() {
        // TODO: test chainId
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'gas'
     */
    @Test
    public void gasTest() {
        // TODO: test gas
    }

    /**
     * Test the property 'gasPrice'
     */
    @Test
    public void gasPriceTest() {
        // TODO: test gasPrice
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'maxFeePerGas'
     */
    @Test
    public void maxFeePerGasTest() {
        // TODO: test maxFeePerGas
    }

    /**
     * Test the property 'maxPriorityFeePerGas'
     */
    @Test
    public void maxPriorityFeePerGasTest() {
        // TODO: test maxPriorityFeePerGas
    }

    /**
     * Test the property 'nonce'
     */
    @Test
    public void nonceTest() {
        // TODO: test nonce
    }

    /**
     * Test the property 'R'
     */
    @Test
    public void RTest() {
        // TODO: test R
    }

    /**
     * Test the property 'S'
     */
    @Test
    public void STest() {
        // TODO: test S
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'transactionIndex'
     */
    @Test
    public void transactionIndexTest() {
        // TODO: test transactionIndex
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'V'
     */
    @Test
    public void VTest() {
        // TODO: test V
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
