/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.qanplatform.model.ResponseLog;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseTransactionReceipt
 */
public class ResponseTransactionReceiptTest {
    private final ResponseTransactionReceipt model = new ResponseTransactionReceipt();

    /**
     * Model tests for ResponseTransactionReceipt
     */
    @Test
    public void testResponseTransactionReceipt() {
        // TODO: test ResponseTransactionReceipt
    }

    /**
     * Test the property 'blockHash'
     */
    @Test
    public void blockHashTest() {
        // TODO: test blockHash
    }

    /**
     * Test the property 'blockNumber'
     */
    @Test
    public void blockNumberTest() {
        // TODO: test blockNumber
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'cumulativeGasUsed'
     */
    @Test
    public void cumulativeGasUsedTest() {
        // TODO: test cumulativeGasUsed
    }

    /**
     * Test the property 'effectiveGasPrice'
     */
    @Test
    public void effectiveGasPriceTest() {
        // TODO: test effectiveGasPrice
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'gasUsed'
     */
    @Test
    public void gasUsedTest() {
        // TODO: test gasUsed
    }

    /**
     * Test the property 'logs'
     */
    @Test
    public void logsTest() {
        // TODO: test logs
    }

    /**
     * Test the property 'logsBloom'
     */
    @Test
    public void logsBloomTest() {
        // TODO: test logsBloom
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'transactionHash'
     */
    @Test
    public void transactionHashTest() {
        // TODO: test transactionHash
    }

    /**
     * Test the property 'transactionIndex'
     */
    @Test
    public void transactionIndexTest() {
        // TODO: test transactionIndex
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
