/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.qanplatform.model.ResponseTransaction;
import com.qanplatform.model.ResponseWithdrawals;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseBlock
 */
public class ResponseBlockTest {
    private final ResponseBlock model = new ResponseBlock();

    /**
     * Model tests for ResponseBlock
     */
    @Test
    public void testResponseBlock() {
        // TODO: test ResponseBlock
    }

    /**
     * Test the property 'baseFeePerGas'
     */
    @Test
    public void baseFeePerGasTest() {
        // TODO: test baseFeePerGas
    }

    /**
     * Test the property 'difficulty'
     */
    @Test
    public void difficultyTest() {
        // TODO: test difficulty
    }

    /**
     * Test the property 'extraData'
     */
    @Test
    public void extraDataTest() {
        // TODO: test extraData
    }

    /**
     * Test the property 'gasLimit'
     */
    @Test
    public void gasLimitTest() {
        // TODO: test gasLimit
    }

    /**
     * Test the property 'gasUsed'
     */
    @Test
    public void gasUsedTest() {
        // TODO: test gasUsed
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

    /**
     * Test the property 'logsBloom'
     */
    @Test
    public void logsBloomTest() {
        // TODO: test logsBloom
    }

    /**
     * Test the property 'miner'
     */
    @Test
    public void minerTest() {
        // TODO: test miner
    }

    /**
     * Test the property 'mixHash'
     */
    @Test
    public void mixHashTest() {
        // TODO: test mixHash
    }

    /**
     * Test the property 'nonce'
     */
    @Test
    public void nonceTest() {
        // TODO: test nonce
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'parentHash'
     */
    @Test
    public void parentHashTest() {
        // TODO: test parentHash
    }

    /**
     * Test the property 'receiptsRoot'
     */
    @Test
    public void receiptsRootTest() {
        // TODO: test receiptsRoot
    }

    /**
     * Test the property 'sha3Uncles'
     */
    @Test
    public void sha3UnclesTest() {
        // TODO: test sha3Uncles
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'stateRoot'
     */
    @Test
    public void stateRootTest() {
        // TODO: test stateRoot
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'totalDifficulty'
     */
    @Test
    public void totalDifficultyTest() {
        // TODO: test totalDifficulty
    }

    /**
     * Test the property 'transactions'
     */
    @Test
    public void transactionsTest() {
        // TODO: test transactions
    }

    /**
     * Test the property 'transactionsRoot'
     */
    @Test
    public void transactionsRootTest() {
        // TODO: test transactionsRoot
    }

    /**
     * Test the property 'uncles'
     */
    @Test
    public void unclesTest() {
        // TODO: test uncles
    }

    /**
     * Test the property 'withdrawals'
     */
    @Test
    public void withdrawalsTest() {
        // TODO: test withdrawals
    }

    /**
     * Test the property 'withdrawalsRoot'
     */
    @Test
    public void withdrawalsRootTest() {
        // TODO: test withdrawalsRoot
    }

}
