/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ResponseLog
 */
public class ResponseLogTest {
    private final ResponseLog model = new ResponseLog();

    /**
     * Model tests for ResponseLog
     */
    @Test
    public void testResponseLog() {
        // TODO: test ResponseLog
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'blockHash'
     */
    @Test
    public void blockHashTest() {
        // TODO: test blockHash
    }

    /**
     * Test the property 'blockNumber'
     */
    @Test
    public void blockNumberTest() {
        // TODO: test blockNumber
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'logIndex'
     */
    @Test
    public void logIndexTest() {
        // TODO: test logIndex
    }

    /**
     * Test the property 'removed'
     */
    @Test
    public void removedTest() {
        // TODO: test removed
    }

    /**
     * Test the property 'topics'
     */
    @Test
    public void topicsTest() {
        // TODO: test topics
    }

    /**
     * Test the property 'transactionHash'
     */
    @Test
    public void transactionHashTest() {
        // TODO: test transactionHash
    }

    /**
     * Test the property 'transactionIndex'
     */
    @Test
    public void transactionIndexTest() {
        // TODO: test transactionIndex
    }

}
