/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SyncStatus
 */
public class SyncStatusTest {
    private final SyncStatus model = new SyncStatus();

    /**
     * Model tests for SyncStatus
     */
    @Test
    public void testSyncStatus() {
        // TODO: test SyncStatus
    }

    /**
     * Test the property 'currentBlock'
     */
    @Test
    public void currentBlockTest() {
        // TODO: test currentBlock
    }

    /**
     * Test the property 'highestBlock'
     */
    @Test
    public void highestBlockTest() {
        // TODO: test highestBlock
    }

    /**
     * Test the property 'startingBlock'
     */
    @Test
    public void startingBlockTest() {
        // TODO: test startingBlock
    }

}
