/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.qanplatform.invoker.JSON;

/**
 * EstimateGasObject
 */

public class EstimateGasObject {
  public static final String SERIALIZED_NAME_BALANCE = "Balance";
  @SerializedName(SERIALIZED_NAME_BALANCE)
  private String balance;

  public static final String SERIALIZED_NAME_CODE = "Code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_NONCE = "Nonce";
  @SerializedName(SERIALIZED_NAME_NONCE)
  private String nonce;

  public static final String SERIALIZED_NAME_STATE = "State";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_STATE_DIFF = "StateDiff";
  @SerializedName(SERIALIZED_NAME_STATE_DIFF)
  private String stateDiff;

  public EstimateGasObject() {
  }

  public EstimateGasObject balance(String balance) {
    this.balance = balance;
    return this;
  }

  /**
   * Fake balance to set for the account before executing the call
   * @return balance
   */
  @javax.annotation.Nullable
  public String getBalance() {
    return balance;
  }

  public void setBalance(String balance) {
    this.balance = balance;
  }


  public EstimateGasObject code(Integer code) {
    this.code = code;
    return this;
  }

  /**
   * Fake EVM bytecode to inject into the account before executing the call
   * @return code
   */
  @javax.annotation.Nullable
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }


  public EstimateGasObject nonce(String nonce) {
    this.nonce = nonce;
    return this;
  }

  /**
   * Fake nonce to set for the account before executing the call
   * @return nonce
   */
  @javax.annotation.Nullable
  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }


  public EstimateGasObject state(String state) {
    this.state = state;
    return this;
  }

  /**
   * Fake key-value mapping to override all slots in the account storage before executing the call
   * @return state
   */
  @javax.annotation.Nullable
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }


  public EstimateGasObject stateDiff(String stateDiff) {
    this.stateDiff = stateDiff;
    return this;
  }

  /**
   * Fake key-value mapping to override individual slots in the account storage before executing the call
   * @return stateDiff
   */
  @javax.annotation.Nullable
  public String getStateDiff() {
    return stateDiff;
  }

  public void setStateDiff(String stateDiff) {
    this.stateDiff = stateDiff;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstimateGasObject estimateGasObject = (EstimateGasObject) o;
    return Objects.equals(this.balance, estimateGasObject.balance) &&
        Objects.equals(this.code, estimateGasObject.code) &&
        Objects.equals(this.nonce, estimateGasObject.nonce) &&
        Objects.equals(this.state, estimateGasObject.state) &&
        Objects.equals(this.stateDiff, estimateGasObject.stateDiff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance, code, nonce, state, stateDiff);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstimateGasObject {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateDiff: ").append(toIndentedString(stateDiff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Balance");
    openapiFields.add("Code");
    openapiFields.add("Nonce");
    openapiFields.add("State");
    openapiFields.add("StateDiff");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EstimateGasObject
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EstimateGasObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EstimateGasObject is not found in the empty JSON string", EstimateGasObject.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EstimateGasObject.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EstimateGasObject` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("Balance") != null && !jsonObj.get("Balance").isJsonNull()) && !jsonObj.get("Balance").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Balance` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Balance").toString()));
      }
      if ((jsonObj.get("Nonce") != null && !jsonObj.get("Nonce").isJsonNull()) && !jsonObj.get("Nonce").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Nonce` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Nonce").toString()));
      }
      if ((jsonObj.get("State") != null && !jsonObj.get("State").isJsonNull()) && !jsonObj.get("State").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `State` to be a primitive type in the JSON string but got `%s`", jsonObj.get("State").toString()));
      }
      if ((jsonObj.get("StateDiff") != null && !jsonObj.get("StateDiff").isJsonNull()) && !jsonObj.get("StateDiff").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `StateDiff` to be a primitive type in the JSON string but got `%s`", jsonObj.get("StateDiff").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EstimateGasObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EstimateGasObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EstimateGasObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EstimateGasObject.class));

       return (TypeAdapter<T>) new TypeAdapter<EstimateGasObject>() {
           @Override
           public void write(JsonWriter out, EstimateGasObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EstimateGasObject read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EstimateGasObject given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EstimateGasObject
   * @throws IOException if the JSON string is invalid with respect to EstimateGasObject
   */
  public static EstimateGasObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EstimateGasObject.class);
  }

  /**
   * Convert an instance of EstimateGasObject to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

