/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.qanplatform.invoker.JSON;

/**
 * FilterObject
 */

public class FilterObject {
  public static final String SERIALIZED_NAME_ADDRESS = "Address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_FROM_BLOCK = "FromBlock";
  @SerializedName(SERIALIZED_NAME_FROM_BLOCK)
  private String fromBlock;

  public static final String SERIALIZED_NAME_TO_BLOCK = "ToBlock";
  @SerializedName(SERIALIZED_NAME_TO_BLOCK)
  private String toBlock;

  public static final String SERIALIZED_NAME_TOPICS = "Topics";
  @SerializedName(SERIALIZED_NAME_TOPICS)
  private List<String> topics = new ArrayList<>();

  public FilterObject() {
  }

  public FilterObject address(String address) {
    this.address = address;
    return this;
  }

  /**
   * The contract address or a list of addresses from which logs should originate
   * @return address
   */
  @javax.annotation.Nonnull
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }


  public FilterObject fromBlock(String fromBlock) {
    this.fromBlock = fromBlock;
    return this;
  }

  /**
   * Get fromBlock
   * @return fromBlock
   */
  @javax.annotation.Nonnull
  public String getFromBlock() {
    return fromBlock;
  }

  public void setFromBlock(String fromBlock) {
    this.fromBlock = fromBlock;
  }


  public FilterObject toBlock(String toBlock) {
    this.toBlock = toBlock;
    return this;
  }

  /**
   * Get toBlock
   * @return toBlock
   */
  @javax.annotation.Nonnull
  public String getToBlock() {
    return toBlock;
  }

  public void setToBlock(String toBlock) {
    this.toBlock = toBlock;
  }


  public FilterObject topics(List<String> topics) {
    this.topics = topics;
    return this;
  }

  public FilterObject addTopicsItem(String topicsItem) {
    if (this.topics == null) {
      this.topics = new ArrayList<>();
    }
    this.topics.add(topicsItem);
    return this;
  }

  /**
   * Get topics
   * @return topics
   */
  @javax.annotation.Nonnull
  public List<String> getTopics() {
    return topics;
  }

  public void setTopics(List<String> topics) {
    this.topics = topics;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterObject filterObject = (FilterObject) o;
    return Objects.equals(this.address, filterObject.address) &&
        Objects.equals(this.fromBlock, filterObject.fromBlock) &&
        Objects.equals(this.toBlock, filterObject.toBlock) &&
        Objects.equals(this.topics, filterObject.topics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, fromBlock, toBlock, topics);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterObject {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    fromBlock: ").append(toIndentedString(fromBlock)).append("\n");
    sb.append("    toBlock: ").append(toIndentedString(toBlock)).append("\n");
    sb.append("    topics: ").append(toIndentedString(topics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Address");
    openapiFields.add("FromBlock");
    openapiFields.add("ToBlock");
    openapiFields.add("Topics");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Address");
    openapiRequiredFields.add("FromBlock");
    openapiRequiredFields.add("ToBlock");
    openapiRequiredFields.add("Topics");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FilterObject
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FilterObject.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FilterObject is not found in the empty JSON string", FilterObject.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FilterObject.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FilterObject` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FilterObject.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("Address").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Address` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Address").toString()));
      }
      if (!jsonObj.get("FromBlock").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FromBlock` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FromBlock").toString()));
      }
      if (!jsonObj.get("ToBlock").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ToBlock` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ToBlock").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("Topics") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("Topics").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `Topics` to be an array in the JSON string but got `%s`", jsonObj.get("Topics").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FilterObject.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FilterObject' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FilterObject> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FilterObject.class));

       return (TypeAdapter<T>) new TypeAdapter<FilterObject>() {
           @Override
           public void write(JsonWriter out, FilterObject value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FilterObject read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FilterObject given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FilterObject
   * @throws IOException if the JSON string is invalid with respect to FilterObject
   */
  public static FilterObject fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FilterObject.class);
  }

  /**
   * Convert an instance of FilterObject to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

