/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.qanplatform.model.EstimateGasObject;
import com.qanplatform.model.ParamsTransaction;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.qanplatform.invoker.JSON;

/**
 * InputEstimateGas
 */

public class InputEstimateGas {
  public static final String SERIALIZED_NAME_$_SCHEMA = "$schema";
  @SerializedName(SERIALIZED_NAME_$_SCHEMA)
  private URI $schema;

  public static final String SERIALIZED_NAME_OBJECT = "Object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private EstimateGasObject _object;

  public static final String SERIALIZED_NAME_TRANSACTION = "Transaction";
  @SerializedName(SERIALIZED_NAME_TRANSACTION)
  private ParamsTransaction transaction;

  public InputEstimateGas() {
  }

  public InputEstimateGas(
     URI $schema
  ) {
    this();
    this.$schema = $schema;
  }

  /**
   * A URL to the JSON Schema for this object.
   * @return $schema
   */
  @javax.annotation.Nullable
  public URI get$Schema() {
    return $schema;
  }



  public InputEstimateGas _object(EstimateGasObject _object) {
    this._object = _object;
    return this;
  }

  /**
   * The state override set with address-to-state mapping where each address maps to an object containing
   * @return _object
   */
  @javax.annotation.Nullable
  public EstimateGasObject getObject() {
    return _object;
  }

  public void setObject(EstimateGasObject _object) {
    this._object = _object;
  }


  public InputEstimateGas transaction(ParamsTransaction transaction) {
    this.transaction = transaction;
    return this;
  }

  /**
   * The transaction call object
   * @return transaction
   */
  @javax.annotation.Nonnull
  public ParamsTransaction getTransaction() {
    return transaction;
  }

  public void setTransaction(ParamsTransaction transaction) {
    this.transaction = transaction;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InputEstimateGas inputEstimateGas = (InputEstimateGas) o;
    return Objects.equals(this.$schema, inputEstimateGas.$schema) &&
        Objects.equals(this._object, inputEstimateGas._object) &&
        Objects.equals(this.transaction, inputEstimateGas.transaction);
  }

  @Override
  public int hashCode() {
    return Objects.hash($schema, _object, transaction);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InputEstimateGas {\n");
    sb.append("    $schema: ").append(toIndentedString($schema)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("$schema");
    openapiFields.add("Object");
    openapiFields.add("Transaction");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Transaction");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to InputEstimateGas
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InputEstimateGas.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InputEstimateGas is not found in the empty JSON string", InputEstimateGas.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!InputEstimateGas.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InputEstimateGas` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InputEstimateGas.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("$schema") != null && !jsonObj.get("$schema").isJsonNull()) && !jsonObj.get("$schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `$schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$schema").toString()));
      }
      // validate the optional field `Object`
      if (jsonObj.get("Object") != null && !jsonObj.get("Object").isJsonNull()) {
        EstimateGasObject.validateJsonElement(jsonObj.get("Object"));
      }
      // validate the required field `Transaction`
      ParamsTransaction.validateJsonElement(jsonObj.get("Transaction"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InputEstimateGas.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InputEstimateGas' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InputEstimateGas> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InputEstimateGas.class));

       return (TypeAdapter<T>) new TypeAdapter<InputEstimateGas>() {
           @Override
           public void write(JsonWriter out, InputEstimateGas value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InputEstimateGas read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of InputEstimateGas given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of InputEstimateGas
   * @throws IOException if the JSON string is invalid with respect to InputEstimateGas
   */
  public static InputEstimateGas fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InputEstimateGas.class);
  }

  /**
   * Convert an instance of InputEstimateGas to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

