/*
 * QAN AutoApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qanplatform.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.qanplatform.invoker.JSON;

/**
 * SyncStatus
 */

public class SyncStatus {
  public static final String SERIALIZED_NAME_CURRENT_BLOCK = "CurrentBlock";
  @SerializedName(SERIALIZED_NAME_CURRENT_BLOCK)
  private String currentBlock;

  public static final String SERIALIZED_NAME_HIGHEST_BLOCK = "HighestBlock";
  @SerializedName(SERIALIZED_NAME_HIGHEST_BLOCK)
  private String highestBlock;

  public static final String SERIALIZED_NAME_STARTING_BLOCK = "StartingBlock";
  @SerializedName(SERIALIZED_NAME_STARTING_BLOCK)
  private String startingBlock;

  public SyncStatus() {
  }

  public SyncStatus currentBlock(String currentBlock) {
    this.currentBlock = currentBlock;
    return this;
  }

  /**
   * The current block, same as getFilterChangesblockNumber encoded as decimal
   * @return currentBlock
   */
  @javax.annotation.Nonnull
  public String getCurrentBlock() {
    return currentBlock;
  }

  public void setCurrentBlock(String currentBlock) {
    this.currentBlock = currentBlock;
  }


  public SyncStatus highestBlock(String highestBlock) {
    this.highestBlock = highestBlock;
    return this;
  }

  /**
   * The estimated highest block encoded as decimal
   * @return highestBlock
   */
  @javax.annotation.Nonnull
  public String getHighestBlock() {
    return highestBlock;
  }

  public void setHighestBlock(String highestBlock) {
    this.highestBlock = highestBlock;
  }


  public SyncStatus startingBlock(String startingBlock) {
    this.startingBlock = startingBlock;
    return this;
  }

  /**
   * The block at which the import started encoded as decimal
   * @return startingBlock
   */
  @javax.annotation.Nonnull
  public String getStartingBlock() {
    return startingBlock;
  }

  public void setStartingBlock(String startingBlock) {
    this.startingBlock = startingBlock;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SyncStatus syncStatus = (SyncStatus) o;
    return Objects.equals(this.currentBlock, syncStatus.currentBlock) &&
        Objects.equals(this.highestBlock, syncStatus.highestBlock) &&
        Objects.equals(this.startingBlock, syncStatus.startingBlock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentBlock, highestBlock, startingBlock);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SyncStatus {\n");
    sb.append("    currentBlock: ").append(toIndentedString(currentBlock)).append("\n");
    sb.append("    highestBlock: ").append(toIndentedString(highestBlock)).append("\n");
    sb.append("    startingBlock: ").append(toIndentedString(startingBlock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CurrentBlock");
    openapiFields.add("HighestBlock");
    openapiFields.add("StartingBlock");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("CurrentBlock");
    openapiRequiredFields.add("HighestBlock");
    openapiRequiredFields.add("StartingBlock");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SyncStatus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SyncStatus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SyncStatus is not found in the empty JSON string", SyncStatus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SyncStatus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SyncStatus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SyncStatus.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("CurrentBlock").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CurrentBlock` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CurrentBlock").toString()));
      }
      if (!jsonObj.get("HighestBlock").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `HighestBlock` to be a primitive type in the JSON string but got `%s`", jsonObj.get("HighestBlock").toString()));
      }
      if (!jsonObj.get("StartingBlock").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `StartingBlock` to be a primitive type in the JSON string but got `%s`", jsonObj.get("StartingBlock").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SyncStatus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SyncStatus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SyncStatus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SyncStatus.class));

       return (TypeAdapter<T>) new TypeAdapter<SyncStatus>() {
           @Override
           public void write(JsonWriter out, SyncStatus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SyncStatus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SyncStatus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SyncStatus
   * @throws IOException if the JSON string is invalid with respect to SyncStatus
   */
  public static SyncStatus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SyncStatus.class);
  }

  /**
   * Convert an instance of SyncStatus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

